name: Tweet Every 20 Seconds

on:
  schedule:
    - cron: '*/1 * * * *' 
  workflow_dispatch: 

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Send Tweet (1st time)
        run: curl -X POST "https://tweeter-automation-six.vercel.app/tweet"

      - name: Wait 20 seconds
        run: sleep 20

      - name: Send Tweet (2nd time)
        run: curl -X POST "https://tweeter-automation-six.vercel.app/tweet"

      - name: Wait 20 seconds
        run: sleep 20

      - name: Send Tweet (3rd time)
        run: curl -X POST "https://tweeter-automation-six.vercel.app/tweet"
