name: Tweet Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'  
  workflow_dispatch:  

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Send Tweet (Once every 4 hours)
        run: curl -X POST "https://tweeter-automation-six.vercel.app/tweet"
